[main]
max_room_list_display = 20

# Database configuration
# In default, it's running in MariaDB.
[database]
address = 'localhost'
db_name = 'werefemboy'
user_name = 'werefemboy'
password = 'password'

[authentication]
# secret_key_file = ''
secret_key = 'weepingdogel'
algorithm = 'HS256'
access_token_expire_minutes = 1440

[static]
static_directory = 'static'
